server:
  port: 8081
spring:
  application:
    name: "Loans"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    default: "dev"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
routes:
  paths:
    loans: "/api/v1/loans"
    loansById: "/api/v1/loans/{id}"
    loansPageable: "/api/v1/loans/pageable"
    loansChangeStatus: "/api/v1/loans/change-status"
springdoc:
  api-docs:
    path: "/v3/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"
    operationsSorter: "alpha"
    tagsSorter: "alpha"
logging:
  level:
    root: "INFO"
    org.springframework.web: "DEBUG"
    org.springframework.security: "DEBUG"
    software.amazon.awssdk.auth: DEBUG
    software.amazon.awssdk.request: DEBUG
    software.amazon.awssdk.services.sqs: DEBUG
